<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TableAuditReport</name>
   <tag></tag>
   <elementGuidId>90b16faa-e39a-4450-9770-105fe65ad095</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='auditReport']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#auditReport</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;auditReport&quot;)[count(. | //table[@id = 'auditReport']) = count(//table[@id = 'auditReport'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>table</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>auditReport</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>table table-hover table-striped table-bordered dt-responsive nowrap dataTable no-footer dtr-inline</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>grid</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>auditReport_info</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
					
					TransactionTaskDateUserDevice
					
					20199Add Sample XML Request2021/01/08 08:37:43linxKatalon20198Add Sample XML Request2021/01/08 08:36:16linxKatalon20197Add Sample XML Request2021/01/08 08:35:13linxKatalon20196Add Sample XML Request2021/01/08 08:33:40linxKatalon20195Add Sample XML Request2021/01/08 08:23:41linxDanielLaptop20194Add Sample XML Request2021/01/08 08:23:03linxDanielLaptop20183Add Sample XML Request2021/01/07 20:16:40linxKatalon20182Add Sample XML Request2021/01/07 20:15:41linxAutomated20181Add Sample XML Request2021/01/07 20:14:41linxAutomaticaly20178Add Sample XML Request2021/01/07 20:09:42linxKatalon</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;auditReport&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//table[@id='auditReport']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='auditReport_wrapper']/table</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Required'])[2]/following::table[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Device'])[2]/following::table[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//table</value>
   </webElementXpaths>
</WebElementEntity>
